//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarselMubarakshin321_UhetPets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets
    {
        public int PetID { get; set; }
        public string Names { get; set; }
        public string Opisanie { get; set; }
        public string ImagePath { get; set; }
    }
}
